const stations = [
  {
    "id": "GBN-A01",
    "name": "DLF Mall Of India Charger (Glida/Statiq)",
    "district": "Gautam Buddha Nagar",
    "capacity": "Multiple Connectors (e.g., 60kW DC, 7.5kW AC)",
    "type": "AC/DC",
    "timing": "Mall Hours (e.g., 11 AM - 11 PM) but chargers are often accessible longer.",
    "location": "Plot M-03, Sector 18, Noida, Uttar Pradesh (P1 Parking)",
    "state": "Uttar Pradesh",
    "lat": 28.5705,
    "lng": 77.3230,
    "contact": "+91-964-330-1116 (Mall Info), Statiq Customer Care (8070743743)",
    "rating": 4.5,
    "source": "PlugShare / Statiq / DLF"
  },
  {
    "id": "GBN-B01",
    "name": "Tata Power - Wave One Sec 18",
    "district": "Gautam Buddha Nagar",
    "capacity": "5 Slots",
    "type": "AC",
    "timing": "9 AM - 9 PM",
    "location": "Wave One, Plot L2a L2a1, Sector 18, Noida",
    "state": "Uttar Pradesh",
    "lat": 28.5715,
    "lng": 77.3250,
    "contact": "8527000290",
    "rating": 4.2,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B02",
    "name": "Statiq - Candor N2 Noida",
    "district": "Gautam Buddha Nagar",
    "capacity": "4 Slots",
    "type": "AC",
    "timing": "8 AM - 8 PM",
    "location": "Plot No 20, 21, Noida-Greater Noida Expy, Sector 135",
    "state": "Uttar Pradesh",
    "lat": 28.4822,
    "lng": 77.5065,
    "contact": "8070743743",
    "rating": 4.0,
    "source": "ZigWheels / Statiq"
  },
  {
    "id": "GBN-B03",
    "name": "Charger - Tejson Motors",
    "district": "Gautam Buddha Nagar",
    "capacity": "1 Slot",
    "type": "AC",
    "timing": "10 AM - 6 PM",
    "location": "Near Metro Station, Block C, Sector 101",
    "state": "Uttar Pradesh",
    "lat": 28.6045,
    "lng": 77.3365,
    "contact": "7829330410",
    "rating": 3.8,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B04",
    "name": "Tata Power - Hotel Hyphen Business",
    "district": "Gautam Buddha Nagar",
    "capacity": "4 Slots",
    "type": "AC",
    "timing": "24/7",
    "location": "Hyphen Business hotel C 45 Sector-62 Noida",
    "state": "Uttar Pradesh",
    "lat": 28.5578,
    "lng": 77.3715,
    "contact": "8527000290",
    "rating": 4.1,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B05",
    "name": "Tata Power - Ginger Hotel, Sector-63",
    "district": "Gautam Buddha Nagar",
    "capacity": "2 Slots",
    "type": "AC",
    "timing": "24/7",
    "location": "Ginger Hotel Noida East Block-H, Sector-63",
    "state": "Uttar Pradesh",
    "lat": 28.5535,
    "lng": 77.3805,
    "contact": "9223581898",
    "rating": 4.0,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B07",
    "name": "Tata Power - Fujitsu Consulting Sec 63",
    "district": "Gautam Buddha Nagar",
    "capacity": "7 Slots",
    "type": "AC",
    "timing": "9 AM - 6 PM",
    "location": "FUJITSU CONSULTING INDIA PVT LTD A-207 SECTOR-63",
    "state": "Uttar Pradesh",
    "latitude": 28.5512,
    "longitude": 77.3822,
    "contact": "9223581898",
    "rating": 4.2,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B08",
    "name": "Statiq - India Glycols Tech Park",
    "district": "Gautam Buddha Nagar",
    "capacity": "4 Slots",
    "type": "AC",
    "timing": "24/7",
    "location": "Upper Basement, India Glycols Tech Park, Sector 126",
    "state": "Uttar Pradesh",
    "latitude": 28.4712,
    "longitude": 77.5142,
    "contact": "01203090100",
    "rating": 3.9,
    "source": "ZigWheels / Statiq"
  },
  {
    "id": "GBN-B09",
    "name": "EVI Technologies - Adhoc Mangalam",
    "district": "Gautam Buddha Nagar",
    "capacity": "2 Slots",
    "type": "DC",
    "timing": "24/7",
    "location": "Km Stone 95.6 Eastern Peripheral Expressway",
    "state": "Uttar Pradesh",
    "latitude": 28.3845,
    "longitude": 77.7125,
    "contact": "9876543210",
    "rating": 3.7,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B10",
    "name": "Charger - Auto Worx",
    "district": "Gautam Buddha Nagar",
    "capacity": "1 Slot",
    "type": "AC",
    "timing": "9 AM - 7 PM",
    "location": "BS-1, near Little Millenium school, Sector 117",
    "state": "Uttar Pradesh",
    "latitude": 28.4555,
    "longitude": 77.4892,
    "contact": "8744988449",
    "rating": 3.6,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B11",
    "name": "Tata Power - Gaur City Avenue",
    "district": "Gautam Buddha Nagar",
    "capacity": "3 Slots",
    "type": "AC",
    "timing": "8 AM - 10 PM",
    "location": "5th Avenue Gaur City 1",
    "state": "Uttar Pradesh",
    "latitude": 28.5295,
    "longitude": 77.3652,
    "contact": "9246419559",
    "rating": 4.3,
    "source": "ZigWheels"
  },
  {
    "id": "LKH-01",
    "name": "IOCL - Aarvi Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Behraich Road, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9500,
    "longitude": 80.7800,
    "contact": "7505608076",
    "rating": 4.1,
    "source": "IOCL"
  },
  {
    "id": "LKH-02",
    "name": "IOCL - Kamla Kisan Sewa Kendra",
    "district": "Lakhimpur Kheri",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "24/7",
    "location": "NH-730, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9200,
    "longitude": 80.7700,
    "contact": "8858706711",
    "rating": 4.2,
    "source": "IOCL"
  },
  {
    "id": "LKH-03",
    "name": "IOCL - Radha Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Bharat DC-001",
    "type": "DC",
    "timing": "10 AM - 7 PM",
    "location": "Bijwa Road, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9400,
    "longitude": 80.7900,
    "contact": "7985304122",
    "rating": 4.0,
    "source": "IOCL"
  },
  {
    "id": "LKH-04",
    "name": "HPCL - Hamara Pump Malti Devi",
    "district": "Lakhimpur Kheri",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "24/7",
    "location": "Vill - Sunderwal, Bijwa Road",
    "state": "Uttar Pradesh",
    "latitude": 27.9300,
    "longitude": 80.7850,
    "contact": "N/A",
    "rating": 4.1,
    "source": "HPCL"
  },
  {
    "id": "LKH-05",
    "name": "HPCL - Raj Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "AC Type 2",
    "type": "AC",
    "timing": "24/7",
    "location": "Main Road, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9550,
    "longitude": 80.7750,
    "contact": "N/A",
    "rating": 4.3,
    "source": "HPCL"
  },
  {
    "id": "LKH-06",
    "name": "IOCL - Sai Baba Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Palia Road, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 28.0000,
    "longitude": 80.8000,
    "contact": "9918300200",
    "rating": 4.2,
    "source": "IOCL"
  },
  {
    "id": "LKH-07",
    "name": "Statiq - Shreyash Filling Station",
    "district": "Lakhimpur Kheri",
    "capacity": "CCS2 DC",
    "type": "DC",
    "timing": "24/7",
    "location": "Behraich Rd, Lakhimpur Kheri-262701",
    "state": "Uttar Pradesh",
    "latitude": 27.9480,
    "longitude": 80.7820,
    "contact": "8070743743",
    "rating": 4.4,
    "source": "Statiq"
  },
  {
    "id": "LKH-08",
    "name": "IOCL - Nanwani Filling Station",
    "district": "Lakhimpur Kheri",
    "capacity": "AC Type 2",
    "type": "AC",
    "timing": "24/7",
    "location": "NH-730A, Lakhimpur",
    "state": "Uttar Pradesh",
    "latitude": 27.9600,
    "longitude": 80.7600,
    "contact": "N/A",
    "rating": 4.0,
    "source": "IOCL"
  },
  {
    "id": "LKH-09",
    "name": "Aman Auto Fuels Charging",
    "district": "Lakhimpur Kheri",
    "capacity": "Bharat DC",
    "type": "DC",
    "timing": "10 AM - 8 PM",
    "location": "Highway, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9350,
    "longitude": 80.7950,
    "contact": "N/A",
    "rating": 4.1,
    "source": "Local"
  },
  {
    "id": "LKH-10",
    "name": "DSCL Pihani Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "AC",
    "type": "AC",
    "timing": "24/7",
    "location": "Pihani Road, Lakhimpur",
    "state": "Uttar Pradesh",
    "latitude": 27.9100,
    "longitude": 80.7800,
    "contact": "N/A",
    "rating": 4.2,
    "source": "DSCL"
  },
  {
    "id": "LKH-11",
    "name": "Achal Bahumukhi Center",
    "district": "Lakhimpur Kheri",
    "capacity": "AC Type 2",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Lakhimpur Town Area",
    "state": "Uttar Pradesh",
    "latitude": 27.9520,
    "longitude": 80.7780,
    "contact": "N/A",
    "rating": 3.9,
    "source": "Local"
  },
  {
    "id": "LKH-12",
    "name": "Karuna Filling Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "24/7",
    "location": "Bijwa Bypass, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9250,
    "longitude": 80.7850,
    "contact": "N/A",
    "rating": 4.0,
    "source": "IOCL"
  },
  {
    "id": "LKH-13",
    "name": "Tata Power - Highway Station",
    "district": "Lakhimpur Kheri",
    "capacity": "CCS-II",
    "type": "DC",
    "timing": "24/7",
    "location": "NH-730, Mailani Road",
    "state": "Uttar Pradesh",
    "latitude": 28.0100,
    "longitude": 80.8100,
    "contact": "18002333555",
    "rating": 4.3,
    "source": "Tata Power"
  },
  {
    "id": "LKH-14",
    "name": "JioBP - Lakhimpur Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Fast DC",
    "type": "DC",
    "timing": "24/7",
    "location": "Behraich Highway",
    "state": "Uttar Pradesh",
    "latitude": 27.9450,
    "longitude": 80.7900,
    "contact": "18008909023",
    "rating": 4.4,
    "source": "JioBP"
  },
  {
    "id": "LKH-15",
    "name": "Statiq - Palia Kalan",
    "district": "Lakhimpur Kheri",
    "capacity": "DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Palia Road, Palia Kalan",
    "state": "Uttar Pradesh",
    "latitude": 28.0200,
    "longitude": 80.8200,
    "contact": "N/A",
    "rating": 4.2,
    "source": "Statiq"
  },
  {
    "id": "LKH-16",
    "name": "HPCL - Nighasan Charging",
    "district": "Lakhimpur Kheri",
    "capacity": "AC",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Nighasan Area, Lakhimpur",
    "state": "Uttar Pradesh",
    "latitude": 28.0500,
    "longitude": 80.8500,
    "contact": "N/A",
    "rating": 4.1,
    "source": "HPCL"
  },
  {
    "id": "LKH-17",
    "name": "IOCL - Mailani KSK",
    "district": "Lakhimpur Kheri",
    "capacity": "Bharat AC",
    "type": "AC",
    "timing": "24/7",
    "location": "Mailani Highway",
    "state": "Uttar Pradesh",
    "latitude": 28.0300,
    "longitude": 80.8300,
    "contact": "N/A",
    "rating": 4.0,
    "source": "IOCL"
  },
  {
    "id": "LKH-18",
    "name": "Ather Grid - Lakhimpur",
    "district": "Lakhimpur Kheri",
    "capacity": "AC Fast",
    "type": "AC",
    "timing": "24/7",
    "location": "Rajendra Nagar, Lakhimpur",
    "state": "Uttar Pradesh",
    "latitude": 27.9650,
    "longitude": 80.7650,
    "contact": "7676600900",
    "rating": 4.3,
    "source": "Ather"
  },
  {
    "id": "LKH-19",
    "name": "Local - Zira Park Station",
    "district": "Lakhimpur Kheri",
    "capacity": "AC Type 2",
    "type": "AC",
    "timing": "10 AM - 8 PM",
    "location": "Zira Park Area",
    "state": "Uttar Pradesh",
    "latitude": 27.9510,
    "longitude": 80.7810,
    "contact": "N/A",
    "rating": 3.8,
    "source": "Local"
  },
  {
    "id": "LKH-20",
    "name": "Statiq - Highway Dhaba",
    "district": "Lakhimpur Kheri",
    "capacity": "CCS2",
    "type": "DC",
    "timing": "24/7",
    "location": "NH-730 Dhaba, Lakhimpur",
    "state": "Uttar Pradesh",
    "latitude": 27.9700,
    "longitude": 80.7500,
    "contact": "N/A",
    "rating": 4.2,
    "source": "Statiq"
  },
  {
    "id": "GBN-B12",
    "name": "Tata Power - GHCL Block B Sector 1",
    "district": "Gautam Buddha Nagar",
    "capacity": "1 Slot",
    "type": "AC",
    "timing": "9 AM - 6 PM",
    "location": "Gujarat Heavy Chemicals LTD B 38 Sector 1",
    "state": "Uttar Pradesh",
    "latitude": 28.5892,
    "longitude": 77.2945,
    "contact": "8527000290",
    "rating": 3.8,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B13",
    "name": "Statiq - AdWall Parsavnath Prestige",
    "district": "Gautam Buddha Nagar",
    "capacity": "4 Slots",
    "type": "AC",
    "timing": "24/7",
    "location": "Exit Gate, Near Badminton Court, Sector 93A",
    "state": "Uttar Pradesh",
    "latitude": 28.5078,
    "longitude": 77.2765,
    "contact": "8070743743",
    "rating": 4.1,
    "source": "ZigWheels / Statiq"
  },
  {
    "id": "GBN-B14",
    "name": "Fortum - Jaypee Charging Station",
    "district": "Gautam Buddha Nagar",
    "capacity": "5 Slots",
    "type": "DC",
    "timing": "24/7",
    "location": "Jaypee Infratech Km-16",
    "state": "Uttar Pradesh",
    "latitude": 28.4165,
    "longitude": 77.6235,
    "contact": "8527000290",
    "rating": 4.4,
    "source": "ZigWheels / Fortum"
  },
  {
    "id": "GBN-B15",
    "name": "Tata Power - Sagar Surajpur",
    "district": "Gautam Buddha Nagar",
    "capacity": "4 Slots",
    "type": "DC",
    "timing": "24/7",
    "location": "E-36 Block E Industrial Area Surajpur Site 4",
    "state": "Uttar Pradesh",
    "latitude": 28.4298,
    "longitude": 77.6508,
    "contact": "8527000290",
    "rating": 4.0,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B16",
    "name": "Statiq - Windsor Grand",
    "district": "Gautam Buddha Nagar",
    "capacity": "2 Slots",
    "type": "AC",
    "timing": "24/7",
    "location": "Near BMS Office, Plot number 1 C, Sector 126",
    "state": "Uttar Pradesh",
    "latitude": 28.4742,
    "longitude": 77.5168,
    "contact": "8070743743",
    "rating": 3.9,
    "source": "ZigWheels / Statiq"
  },
  {
    "id": "GBN-B17",
    "name": "Charger - Vikrant Electricals",
    "district": "Gautam Buddha Nagar",
    "capacity": "1 Slot",
    "type": "AC",
    "timing": "9 AM - 8 PM",
    "location": "Shop No. 4, Mahendra Complex, Bhangel Sec. 82",
    "state": "Uttar Pradesh",
    "latitude": 28.5182,
    "longitude": 77.3458,
    "contact": "7829330410",
    "rating": 3.5,
    "source": "ZigWheels"
  },
  {
    "id": "GBN-B18",
    "name": "Statiq - N1 Candor Tech Space",
    "district": "Gautam Buddha Nagar",
    "capacity": "4 Slots",
    "type": "AC",
    "timing": "8 AM - 8 PM",
    "location": "Plot No - B, IT/ITES Park, Candor TechSpace, Sector 62",
    "state": "Uttar Pradesh",
    "latitude": 28.5598,
    "longitude": 77.3698,
    "contact": "8070743743",
    "rating": 4.2,
    "source": "ZigWheels / Statiq"
  },
  {
    "id": "GBN-B19",
    "name": "Statiq Gaur Grandeur Station",
    "district": "Gautam Buddha Nagar",
    "capacity": "6 Slots",
    "type": "DC/AC",
    "timing": "24/7",
    "location": "Gaur Grandeur (Noida/Greater Noida)",
    "state": "Uttar Pradesh",
    "latitude": 28.5425,
    "longitude": 77.3565,
    "contact": "8070743743",
    "rating": 4.3,
    "source": "Statiq"
  },
  {
    "id": "GBN-B20",
    "name": "Tata Power- IOCL COCO EPE, Aurangpur",
    "district": "Gautam Buddha Nagar",
    "capacity": "1 DC Charger (CCS-2)",
    "type": "DC",
    "timing": "24/7",
    "location": "Plot CH-95, 600, Village Aurangpur, EPE",
    "state": "Uttar Pradesh",
    "latitude": 28.3652,
    "longitude": 77.7145,
    "contact": "8527000290 (Tata Power)",
    "rating": 4.0,
    "source": "Statiq / Tata Power"
  },
  {
    "id": "GBN-B21",
    "name": "Statiq MLCP Noida Sec-18 Charging Hub",
    "district": "Gautam Buddha Nagar",
    "capacity": "Multiple DC (up to 120kW) and AC chargers",
    "type": "DC/AC",
    "timing": "24/7",
    "location": "Near DLF Mall of India, Noida sector 18 MLCP parking",
    "state": "Uttar Pradesh",
    "latitude": 28.5712,
    "longitude": 77.3242,
    "contact": "8070743743",
    "rating": 4.6,
    "source": "Statiq"
  },
  { "id": "LKO-01", "name": "Hilton Garden Inn", "district": "Lucknow", "capacity": "60kW CCS2 DC", "type": "DC", "timing": "24/7", "location": "Gomti Nagar, Lucknow", "state": "Uttar Pradesh", "latitude": 26.8467, "longitude": 80.9462, "contact": "18004196078", "rating": 4.5, "source": "Statiq" },
  { "id": "LKO-02", "name": "Fun Republic Mall", "district": "Lucknow", "capacity": "30kW DC", "type": "DC", "timing": "10AM-10PM", "location": "Sushant Golf City", "state": "Uttar Pradesh", "latitude": 26.7550, "longitude": 81.1200, "contact": "18004196078", "rating": 4.2, "source": "Statiq" },
  { "id": "LKO-03", "name": "Holiday Inn Airport", "district": "Lucknow", "capacity": "60kW DC Dual Gun", "type": "DC", "timing": "24/7", "location": "Airport Road", "state": "Uttar Pradesh", "latitude": 26.7450, "longitude": 80.8880, "contact": "18004196078", "rating": 4.4, "source": "Sunfuel/Statiq" },
  { "id": "LKO-04", "name": "Clarks Avadh", "district": "Lucknow", "capacity": "30kW DC", "type": "DC", "timing": "24/7", "location": "Mahatma Gandhi Marg", "state": "Uttar Pradesh", "latitude": 26.8393, "longitude": 80.9231, "contact": "18004196078", "rating": 4.1, "source": "E-fill" },
  { "id": "LKO-05", "name": "Taj Mahal FC", "district": "Lucknow", "capacity": "CCS2 DC Fast", "type": "DC", "timing": "24/7", "location": "Faizabad Road", "state": "Uttar Pradesh", "latitude": 26.8000, "longitude": 80.9500, "contact": "18008332233", "rating": 4.3, "source": "Tata Power" },
  { "id": "LKO-06", "name": "Shalimar Gateway Mall", "district": "Lucknow", "capacity": "60kW CCS", "type": "DC", "timing": "10AM-10PM", "location": "Near RBL Road", "state": "Uttar Pradesh", "latitude": 26.8500, "longitude": 80.9500, "contact": "18008332233", "rating": 4.0, "source": "Tata Power" },
  { "id": "LKO-07", "name": "TML SRM Motors", "district": "Lucknow", "capacity": "22kW AC", "type": "AC", "timing": "9AM-7PM", "location": "Faizabad Road", "state": "Uttar Pradesh", "latitude": 26.8460, "longitude": 81.0000, "contact": "18008332233", "rating": 4.6, "source": "Tata" },
  { "id": "LKO-08", "name": "Shalimar Corporate Park", "district": "Lucknow", "capacity": "11kW AC", "type": "AC", "timing": "24/7", "location": "Sahara Bypass", "state": "Uttar Pradesh", "latitude": 26.8700, "longitude": 80.9700, "contact": "18008332233", "rating": 4.2, "source": "Tata Power" },
  { "id": "LKO-09", "name": "Bangla Bazar V Bazaar", "district": "Lucknow", "capacity": "60kW DC", "type": "DC", "timing": "24/7", "location": "Bangla Bazar", "state": "Uttar Pradesh", "latitude": 26.8600, "longitude": 80.9300, "contact": "18008332233", "rating": 4.1, "source": "Tata Power" },
  { "id": "LKO-10", "name": "Novotel Gomti Nagar FC", "district": "Lucknow", "capacity": "CCS2 DC", "type": "DC", "timing": "24/7", "location": "Viraj Khand, Gomti Nagar", "state": "Uttar Pradesh", "latitude": 26.8520, "longitude": 81.0020, "contact": "18008332233", "rating": 4.5, "source": "Tata Power" },
  { "id": "LKO-11", "name": "Ginger Hotel", "district": "Lucknow", "capacity": "30kW DC", "type": "DC", "timing": "24/7", "location": "Gomti Nagar", "state": "Uttar Pradesh", "latitude": 26.8500, "longitude": 81.0000, "contact": "18008332233", "rating": 4.3, "source": "Tata Power" },
  { "id": "LKO-12", "name": "Hotel Elite Convention", "district": "Lucknow", "capacity": "22kW AC", "type": "AC", "timing": "24/7", "location": "Near Airport", "state": "Uttar Pradesh", "latitude": 26.7400, "longitude": 80.8900, "contact": "18008332233", "rating": 4.0, "source": "Tata Power" },
  { "id": "LKO-13", "name": "MG Motors", "district": "Lucknow", "capacity": "60kW CCS", "type": "DC", "timing": "9AM-7PM", "location": "Chinhat", "state": "Uttar Pradesh", "latitude": 26.8200, "longitude": 80.9700, "contact": "18004196078", "rating": 4.4, "source": "Statiq" },
  { "id": "LKO-14", "name": "SAS Hyundai", "district": "Lucknow", "capacity": "AC Type 2", "type": "AC", "timing": "10AM-7PM", "location": "Kanpur Road, Amausi", "state": "Uttar Pradesh", "latitude": 26.7600, "longitude": 80.8800, "contact": "8527000290", "rating": 4.2, "source": "Hyundai" },
  { "id": "LKO-15", "name": "Beeaar Autowheels Chinhat", "district": "Lucknow", "capacity": "CCS2", "type": "DC", "timing": "24/7", "location": "Faizabad Road, Chinhat", "state": "Uttar Pradesh", "latitude": 26.8300, "longitude": 80.9600, "contact": "18008332233", "rating": 4.3, "source": "Tata Power" },
  { "id": "LKO-16", "name": "Pinnacle Charging Station", "district": "Lucknow", "capacity": "CCS2", "type": "DC", "timing": "10AM-7AM", "location": "LDA Colony, Sector D", "state": "Uttar Pradesh", "latitude": 26.8400, "longitude": 80.9900, "contact": "18008332233", "rating": 4.1, "source": "Tata Power" },
  { "id": "LKO-17", "name": "VEVC-72 TiwariGanj", "district": "Lucknow", "capacity": "GB/T", "type": "DC", "timing": "10AM-7PM", "location": "TiwariGanj", "state": "Uttar Pradesh", "latitude": 26.8100, "longitude": 80.9400, "contact": "9711829983", "rating": 3.9, "source": "VEVC" },
  { "id": "LKO-18", "name": "IOCL Sbsd", "district": "Lucknow", "capacity": "Bharat AC001", "type": "AC", "timing": "10AM-7PM", "location": "Dubagga Road, Gopramau", "state": "Uttar Pradesh", "latitude": 26.8800, "longitude": 80.9200, "contact": "9936657432", "rating": 4.0, "source": "IOCL" },
  { "id": "LKO-19", "name": "IOCL Tejas Filling", "district": "Lucknow", "capacity": "AC Type 2", "type": "AC", "timing": "24/7", "location": "Kursi Road, Basha", "state": "Uttar Pradesh", "latitude": 26.8900, "longitude": 80.9500, "contact": "9936657432", "rating": 4.2, "source": "IOCL" },
  { "id": "LKO-20", "name": "Audi Service Lucknow", "district": "Lucknow", "capacity": "AC Plug Point", "type": "AC", "timing": "10AM-7PM", "location": "UPSIDC, Sarojini Nagar", "state": "Uttar Pradesh", "latitude": 26.7700, "longitude": 80.8700, "contact": "8795840010", "rating": 4.6, "source": "Audi" },
  { "id": "LKO-21", "name": "A Automovers", "district": "Lucknow", "capacity": "3Pin AC", "type": "AC", "timing": "10AM-7PM", "location": "Faizabad Road, Chinhut", "state": "Uttar Pradesh", "latitude": 26.8300, "longitude": 80.9500, "contact": "9838076155", "rating": 4.1, "source": "Private" },
  { "id": "LKO-22", "name": "HPCL Bhola Filling", "district": "Lucknow", "capacity": "CCS2", "type": "DC", "timing": "24/7", "location": "Faizabad Road", "state": "Uttar Pradesh", "latitude": 26.8200, "longitude": 80.9600, "contact": "1800224344", "rating": 4.0, "source": "HPCL" },
  { "id": "LKO-23", "name": "Ather Grid Station", "district": "Lucknow", "capacity": "AC", "type": "AC", "timing": "24/7", "location": "Charbagh", "state": "Uttar Pradesh", "latitude": 26.8500, "longitude": 80.9100, "contact": "9599443291", "rating": 4.4, "source": "Ather" },
  { "id": "LKO-24", "name": "Tata Power Novotel Private", "district": "Lucknow", "capacity": "CCS-II", "type": "DC", "timing": "12AM-12AM", "location": "Minar Builders, Gomti Nagar", "state": "Uttar Pradesh", "latitude": 26.8520, "longitude": 81.0020, "contact": "8527000290", "rating": 4.3, "source": "Tata Power" },
  { "id": "LKO-25", "name": "1C Charging Station", "district": "Lucknow", "capacity": "DC Fast", "type": "DC", "timing": "24/7", "location": "Central Lucknow", "state": "Uttar Pradesh", "latitude": 26.8467, "longitude": 80.9462, "contact": "9599443291", "rating": 4.2, "source": "1C" },
  { "id": "LKO-26", "name": "BPCL Naanmau", "district": "Lucknow", "capacity": "AC/DC", "type": "AC", "timing": "24/7", "location": "Barabanki Outskirts", "state": "Uttar Pradesh", "latitude": 26.9000, "longitude": 81.0500, "contact": "1800224344", "rating": 4.1, "source": "BPCL" },
  { "id": "LKO-27", "name": "Statiq Gomti Nagar Extra", "district": "Lucknow", "capacity": "22kW AC", "type": "AC", "timing": "24/7", "location": "Gomti Nagar Extension", "state": "Uttar Pradesh", "latitude": 26.8600, "longitude": 81.0200, "contact": "18004196078", "rating": 4.5, "source": "Statiq" },
  { "id": "LKO-28", "name": "Tata SRM Alambagh", "district": "Lucknow", "capacity": "60kW DC", "type": "DC", "timing": "9AM-7PM", "location": "Alambagh", "state": "Uttar Pradesh", "latitude": 26.8200, "longitude": 80.9000, "contact": "18008332233", "rating": 4.0, "source": "Tata" },
  { "id": "LKO-29", "name": "E-fill Airport Zone", "district": "Lucknow", "capacity": "30kW", "type": "DC", "timing": "24/7", "location": "Near Amausi Airport", "state": "Uttar Pradesh", "latitude": 26.7500, "longitude": 80.8800, "contact": "18004196078", "rating": 4.3, "source": "E-fill" },
  { "id": "LKO-30", "name": "Chargezone LDA", "district": "Lucknow", "capacity": "CCS2", "type": "DC", "timing": "24/7", "location": "LDA Colony", "state": "Uttar Pradesh", "latitude": 26.8400, "longitude": 80.9900, "contact": "N/A", "rating": 4.2, "source": "Chargezone" },
  { "id": "LKO-31", "name": "Statiq Wave Mall", "district": "Lucknow", "capacity": "11kW AC", "type": "AC", "timing": "10AM-10PM", "location": "Telibagh", "state": "Uttar Pradesh", "latitude": 26.7800, "longitude": 80.9200, "contact": "18004196078", "rating": 4.4, "source": "Statiq" },
  { "id": "LKO-32", "name": "Tata Power Kanpur Rd", "district": "Lucknow", "capacity": "AC Type 2", "type": "AC", "timing": "24/7", "location": "Kanpur Road", "state": "Uttar Pradesh", "latitude": 26.7600, "longitude": 80.8800, "contact": "18008332233", "rating": 4.1, "source": "Tata Power" },
  { "id": "LKO-33", "name": "MG Service Chinhat", "district": "Lucknow", "capacity": "60kW CCS", "type": "DC", "timing": "9AM-7PM", "location": "Chinhat Depot", "state": "Uttar Pradesh", "latitude": 26.8200, "longitude": 80.9700, "contact": "18004196078", "rating": 4.5, "source": "MG" },
  { "id": "LKO-34", "name": "IOCL Kursi Rd", "district": "Lucknow", "capacity": "Bharat AC", "type": "AC", "timing": "24/7", "location": "Kursi Road", "state": "Uttar Pradesh", "latitude": 26.8900, "longitude": 80.9500, "contact": "9936657432", "rating": 4.0, "source": "IOCL" },
  { "id": "LKO-35", "name": "Statiq Sahara Mall", "district": "Lucknow", "capacity": "22kW", "type": "AC", "timing": "10AM-10PM", "location": "Sahara Bypass", "state": "Uttar Pradesh", "latitude": 26.8700, "longitude": 80.9700, "contact": "18004196078", "rating": 4.3, "source": "Statiq" },
  { "id": "LKO-36", "name": "Tata Ginger Private", "district": "Lucknow", "capacity": "CCS-II", "type": "DC", "timing": "24/7", "location": "Gomti Nagar", "state": "Uttar Pradesh", "latitude": 26.8500, "longitude": 81.0000, "contact": "18008332233", "rating": 4.2, "source": "Tata Power" },
  { "id": "LKO-37", "name": "Hyundai Amausi", "district": "Lucknow", "capacity": "AC Plug", "type": "AC", "timing": "10AM-7PM", "location": "Amausi Sindhunagar", "state": "Uttar Pradesh", "latitude": 26.7600, "longitude": 80.8800, "contact": "8527000290", "rating": 4.1, "source": "Hyundai" },
  { "id": "LKO-38", "name": "Ather Charbagh", "district": "Lucknow", "capacity": "Fast AC", "type": "AC", "timing": "24/7", "location": "Charbagh Station Area", "state": "Uttar Pradesh", "latitude": 26.8500, "longitude": 80.9100, "contact": "9599443291", "rating": 4.4, "source": "Ather" },
  { "id": "LKO-39", "name": "Statiq Elite Crossing", "district": "Lucknow", "capacity": "60kW DC", "type": "DC", "timing": "24/7", "location": "Civil Lines", "state": "Uttar Pradesh", "latitude": 26.8400, "longitude": 80.9300, "contact": "18004196078", "rating": 4.3, "source": "Statiq" },
  { "id": "LKO-40", "name": "Tata Power BBD Uni", "district": "Lucknow", "capacity": "CCS2", "type": "DC", "timing": "12AM-12AM", "location": "Faizabad Road, Tiwariganj", "state": "Uttar Pradesh", "latitude": 26.8000, "longitude": 80.9500, "contact": "18008332233", "rating": 4.0, "source": "Tata Power" },
  { "id": "LKO-41", "name": "VEVC Gomti", "district": "Lucknow", "capacity": "GB/T", "type": "DC", "timing": "10AM-7PM", "location": "Gomti Nagar", "state": "Uttar Pradesh", "latitude": 26.8520, "longitude": 81.0020, "contact": "9711829983", "rating": 3.8, "source": "VEVC" },
  { "id": "LKO-42", "name": "HPCL Faizabad", "district": "Lucknow", "capacity": "DC Fast", "type": "DC", "timing": "24/7", "location": "Faizabad Road", "state": "Uttar Pradesh", "latitude": 26.8300, "longitude": 80.9600, "contact": "1800224344", "rating": 4.2, "source": "HPCL" },
  { "id": "LKO-43", "name": "Statiq Novotel Extra", "district": "Lucknow", "capacity": "30kW", "type": "DC", "timing": "24/7", "location": "Gomti Nagar", "state": "Uttar Pradesh", "latitude": 26.8520, "longitude": 81.0020, "contact": "18004196078", "rating": 4.5, "source": "Statiq" },
  { "id": "LKO-44", "name": "Tata SRM Sarojini", "district": "Lucknow", "capacity": "22kW AC", "type": "AC", "timing": "9AM-7PM", "location": "Sarojini Nagar", "state": "Uttar Pradesh", "latitude": 26.7700, "longitude": 80.8700, "contact": "18008332233", "rating": 4.1, "source": "Tata" },
  { "id": "LKO-45", "name": "E-fill Shalimar", "district": "Lucknow", "capacity": "AC/DC", "type": "AC", "timing": "24/7", "location": "Shalimar Area", "state": "Uttar Pradesh", "latitude": 26.8500, "longitude": 80.9500, "contact": "18004196078", "rating": 4.3, "source": "E-fill" },
  { "id": "LKO-46", "name": "Chargezone Airport", "district": "Lucknow", "capacity": "60kW CCS", "type": "DC", "timing": "24/7", "location": "Amausi Airport Vicinity", "state": "Uttar Pradesh", "latitude": 26.7450, "longitude": 80.8880, "contact": "N/A", "rating": 4.4, "source": "Chargezone" },
  { "id": "LKO-47", "name": "Statiq Bangla Bazar 2", "district": "Lucknow", "capacity": "11kW Pillar", "type": "AC", "timing": "24/7", "location": "Bangla Bazar Duplicate", "state": "Uttar Pradesh", "latitude": 26.8600, "longitude": 80.9300, "contact": "18004196078", "rating": 4.0, "source": "Statiq" },
  { "id": "LKO-48", "name": "IOCL Dubagga Extra", "district": "Lucknow", "capacity": "Type 2 AC", "type": "AC", "timing": "10AM-7PM", "location": "Dubagga Road", "state": "Uttar Pradesh", "latitude": 26.8800, "longitude": 80.9200, "contact": "9936657432", "rating": 4.2, "source": "IOCL" },
  { "id": "LKO-49", "name": "Tata Power Elite", "district": "Lucknow", "capacity": "CCS2 Fast", "type": "DC", "timing": "24/7", "location": "Hotel Elite Area", "state": "Uttar Pradesh", "latitude": 26.7400, "longitude": 80.8900, "contact": "18008332233", "rating": 4.3, "source": "Tata Power" },
  { "id": "LKO-50", "name": "Athergrid Sushant", "district": "Lucknow", "capacity": "AC Fast", "type": "AC", "timing": "24/7", "location": "Sushant Golf City", "state": "Uttar Pradesh", "latitude": 26.7550, "longitude": 81.1200, "contact": "9599443291", "rating": 4.4, "source": "Ather" },
  {
    "id": "AYD-A01",
    "name": "Statiq - Lakshman Kunj Ayodhya Station",
    "district": "Ayodhya",
    "capacity": "1 DC (120 kW) and 4 AC (3.3 kW each)",
    "type": "DC/AC",
    "timing": "24/7",
    "location": "Civil Line, Basement Parking, Faizabad",
    "state": "Uttar Pradesh",
    "latitude": 26.7721,
    "longitude": 82.1241,
    "contact": "+91-80707-43743 (Statiq Customer Care)",
    "rating": 4.55,
    "source": "Statiq / PlugShare"
  },
  {
    "id": "AYD-A02",
    "name": "Tata Power - Prayag Udyog NH 27 Charging Station",
    "district": "Ayodhya",
    "capacity": "1 DC Slot (High Power)",
    "type": "DC",
    "timing": "24/7",
    "location": "Govt Polytechnic, Lucknow Road, Banbeerpur, Ayodhya",
    "state": "Uttar Pradesh",
    "latitude": 26.7845,
    "longitude": 82.1385,
    "contact": "+91-99623-94941",
    "rating": 5.0,
    "source": "ZigWheels / CarDekho"
  },
  {
    "id": "AYD-A03",
    "name": "Tata Power - Shree Dev Wheels",
    "district": "Ayodhya",
    "capacity": "4 Slots (CHAdeMO - 2, CCS-II - 2)",
    "type": "DC",
    "timing": "10 AM - 7 PM",
    "location": "Plot No 402 and 403 B Sultanpur Road, Acharya Nagar, Ayodhya",
    "state": "Uttar Pradesh",
    "latitude": 26.7925,
    "longitude": 82.1125,
    "contact": "18008332233 (Tata Power Customer Care)",
    "rating": 4.2,
    "source": "ZigWheels"
  },
  {
    "id": "AYD-A04",
    "name": "Tata Power - Shane Avadh Hotel",
    "district": "Ayodhya",
    "capacity": "1 Slot",
    "type": "DC",
    "timing": "24/7",
    "location": "Hotel Shane Avadh, Civil Lines, Ayodhya",
    "state": "Uttar Pradesh",
    "latitude": 26.7765,
    "longitude": 82.1305,
    "contact": "+91-99623-94941",
    "rating": 4.1,
    "source": "ZigWheels / CarDekho"
  },
  {
    "id": "AYD-A05",
    "name": "BPCL - Saket Autostation",
    "district": "Ayodhya",
    "capacity": "1 DC Slot",
    "type": "DC",
    "timing": "24/7",
    "location": "Karsewakpuram, Ayodhya",
    "state": "Uttar Pradesh",
    "latitude": 26.8015,
    "longitude": 82.1445,
    "contact": "+91-80707-43743",
    "rating": 4.0,
    "source": "Statiq / BPCL"
  },
  {
    "id": "AYD-A06",
    "name": "Xobolt Charging Station",
    "district": "Ayodhya",
    "capacity": "2 Slots",
    "type": "DC/AC",
    "timing": "9 AM - 6 PM",
    "location": "Majhwa Gaddou Pur, Civil Line, Jogitara, Ayodhya",
    "state": "Uttar Pradesh",
    "latitude": 26.7685,
    "longitude": 82.1155,
    "contact": "9876543210",
    "rating": 4.4,
    "source": "Justdial"
  },
  {
    "id": "VNS-IOCL-NEELKANTH-01",
    "name": "IOCL Neelkanth Kisan Sewa Kendra Charger",
    "district": "Varanasi",
    "capacity": "2 connectors (Bharat AC-001 + Type-II AC)",
    "type": "AC",
    "timing": "24/7",
    "location": "Lacchirampur, Pindra / Birbhanpur, Varanasi, Uttar Pradesh-221201",
    "state": "Uttar Pradesh",
    "latitude": 25.30081,
    "longitude": 82.80588,
    "contact": "8866260309",
    "image": null,
    "source": "Varanasi EV Infrastructure Report / ZigWheels list"
  },
  {
    "id": "VNS-IOCL-PRABHU-01",
    "name": "IOCL Prabhunarayan Filling Station Charger",
    "district": "Varanasi",
    "capacity": "2 connectors (Bharat AC-001 + Type-II AC)",
    "type": "AC",
    "timing": "24/7",
    "location": "Vill-Dandoopur, Sadar Anai, Varanasi, Uttar Pradesh-221201",
    "state": "Uttar Pradesh",
    "latitude": 25.38673,
    "longitude": 82.95888,
    "contact": "9935611597",
    "image": null,
    "source": "Varanasi EV Infrastructure Report"
  },
  {
    "id": "VNS-IOCL-LERHUPUR-01",
    "name": "IOCL Lerhupur Kisan Sewa Kendra Charger",
    "district": "Varanasi",
    "capacity": "2 connectors (Bharat AC-001 + Type-II AC)",
    "type": "AC",
    "timing": "24/7",
    "location": "Village Lerhupur, Tehsil Sadar, Varanasi, Uttar Pradesh",
    "state": "Uttar Pradesh",
    "latitude": 25.35762,
    "longitude": 83.04477,
    "contact": null,
    "image": null,
    "source": "Varanasi EV Infrastructure Report"
  },
  {
    "id": "GOND-S01",
    "name": "Tata power- dev shree tata motors",
    "district": "Gonda",
    "state": "Uttar Pradesh",
    "location_details": {
      "latitude": 27.13374,
      "longitude": 81.93790,
      "address": "4WMP+FX4, Police Line, Pathwalia, Gonda"
    },
    "charger_details": {
      "type": "AC/DC",
      "speed_class": "Fast Charger",
      "capacity": "1 DC Connector (Up to 25kW) + AC Connector(s)",
      "dc_connector_count": 1,
      "dc_max_kw": 25,
      "ac_connector_count": null
    },
    "operational_info": {
      "timing": "Information not explicitly confirmed as 24/7, check app for real-time status.",
      "contact": "+91 70451 74042 (Operator/Site Contact)",
      "source": "PlugShare/Statiq"
    }
  },
  {
    "id": "PRG-KARTAVYA-01",
    "name": "KARTAVYA AUTOMOBILES Charger",
    "district": "Pratapgarh",
    "capacity": "1 connector (30 kW DC)",
    "type": "DC",
    "timing": "24/7",
    "location": "Pratapgarh, Uttar Pradesh, 230403",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": null,
    "image": null,
    "source": "Statiq EV charging database"
  },
  {
    "id": "PRG-AMBIKA-01",
    "name": "AMBIKA SHANKAR AUTOMOBILES Charger",
    "district": "Pratapgarh",
    "capacity": "1 connector (30 kW DC)",
    "type": "DC",
    "timing": "24/7",
    "location": "Tehsil Pratapgarh, Bahua, Uttar Pradesh, 230404",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": null,
    "image": null,
    "source": "Statiq EV charging database"
  },
  {
    "id": "PRYGJ-J01",
    "name": "JioBP Fast DC Charger CWC Naini",
    "district": "Prayagraj",
    "capacity": "2 CCS2 DC Connectors (Likely 60kW Shared)",
    "type": "DC (Fast Charger)",
    "timing": "24/7",
    "location": "Central Warehouse Corporation (CWC), In-Campus Rd, Naini, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.34537,
    "longitude": 81.89787,
    "contact": null,
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "https://www.plugshare.com/location/723429"
  },
  {
    "id": "PRYGJ-A01",
    "name": "Ather-Asian Paints Store-Rasulabad",
    "district": "Prayagraj",
    "capacity": "3 Connectors (Ather Grid - 3.3kW AC)",
    "type": "AC (Slow Charger - Two/Three Wheeler Focus)",
    "timing": "Varies (Business Hours)",
    "location": "Prayagraj - Pratapgarh Rd, Rasulabad, Teliarganj, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.4851,
    "longitude": 81.8519,
    "contact": "+91 80664 65757 (Ather Support)",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "ZigWheels / Ather Grid"
  },
  {
    "id": "PRYGJ-T01",
    "name": "Tata Power - Cennet Hotel (Private)",
    "district": "Prayagraj",
    "capacity": "1 AC Type 2 Connector (Likely 7.4kW)",
    "type": "AC (Level 2 Charger)",
    "timing": "24/7 (Hotel Parking Access)",
    "location": "Cennet Hotel, 15D, 13/1 Tashkent Marg, Civil Lines, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.4526,
    "longitude": 81.8410,
    "contact": "+91 85270 00290 (Tata Power Contact)",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "CarDekho / Tata Power EZ Charge"
  },
  {
    "id": "PRYGJ-I01",
    "name": "IOCL - ADISHAKTI SUPER MULTI",
    "district": "Prayagraj",
    "capacity": "1 Connector (Bharat AC-001 or Type 2)",
    "type": "AC (Slow/Medium Charger)",
    "timing": "Limited Hours (e.g., 6:00 AM - 10:00 PM)",
    "location": "Kachari, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.4485,
    "longitude": 81.8340,
    "contact": "+91 78293 30410",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "CarDekho / Other Directories"
  },
  {
    "id": "PRYGJ-I02",
    "name": "IOCL - Panjtan Kisan Seva Kendra",
    "district": "Prayagraj",
    "capacity": "2 Connectors (Bharat AC-001, Type-II)",
    "type": "AC (Slow/Medium Charger)",
    "timing": "24/7",
    "location": "Ground Floor, Buapur, Phulpur Soraon, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.5670,
    "longitude": 81.8700,
    "contact": "+91 99183 00200",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "ZigWheels / CarDekho"
  },
  {
    "id": "AGRA-S01",
    "name": "Statiq ITC Mughal Station",
    "district": "Agra",
    "capacity": "2 CCS2 DC Connectors (Up to 120kW Shared) + AC Charger",
    "type": "AC/DC (Fast Charger)",
    "timing": "24/7 (Hotel Parking Access)",
    "location": "ITC Mughal, Tajganj Ground Floor, Fatehabad Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.16077,
    "longitude": 78.04395,
    "contact": "+91 80707 43743 (Statiq Support)",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "https://www.plugshare.com/location/634026"
  },
  {
    "id": "AGRA-T01",
    "name": "Tata Power Trident Hotel Charger",
    "district": "Agra",
    "capacity": "2 CCS2 DC Connectors (Up to 60kW Each)",
    "type": "DC (Fast Charger)",
    "timing": "24/7 (Hotel Parking Access)",
    "location": "Trident Hotel, Fatehabad Rd, Basai Khurd, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.15920,
    "longitude": 78.06084,
    "contact": "+91 81713 69204 (Local Contact) / Tata Power Support",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "https://www.plugshare.com/location/574039"
  },
  {
    "id": "AGRA-I01",
    "name": "IOCL Taj Parking (Indian Oil)",
    "district": "Agra",
    "capacity": "1 CCS2 DC Connector (Up to 60kW)",
    "type": "DC (Fast Charger)",
    "timing": "24/7 (Taj Parking Access)",
    "location": "Shilpgram Ground, Taj Parking, Tajganj, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.16632,
    "longitude": 78.05222,
    "contact": null,
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "https://www.plugshare.com/location/537439"
  },
  {
    "id": "AGRA-U01",
    "name": "UPEIDA Agra Toll Plaza (RHS)",
    "district": "Agra",
    "capacity": "Dual Gun DC Charger (240kW + 60kW)",
    "type": "DC (Ultra-Fast Charger)",
    "timing": "24/7",
    "location": "Agra Toll Plaza (RHS - from Lucknow), Bichola, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.05720,
    "longitude": 78.27274,
    "contact": null,
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "https://www.plugshare.com/location/841724"
  },
  {
    "id": "AGRA-S02",
    "name": "Statiq Jaypee Hotel Station",
    "district": "Agra",
    "capacity": "2 CCS2 DC Connectors (Up to 120kW Shared)",
    "type": "DC (Fast Charger)",
    "timing": "24/7 (Hotel Parking Access)",
    "location": "Jaypee Palace Hotel, Fatehabad Rd, Kalal Kheria, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.15263,
    "longitude": 78.07176,
    "contact": "+91 80707 43743 (Statiq Support)",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "https://www.plugshare.com/location/647767"
  },
  {
    "id": "LK-I01",
    "name": "IOCL - Aarvi Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (Multiple Slots, Likely AC/DC <50kW)",
    "type": "AC/DC (Standard Charger)",
    "timing": "Varies (Call to Confirm)",
    "location": "Ground Floor, Chandan Chauki, Palia Majhgain, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 28.3887,
    "longitude": 80.5750,
    "contact": "+91 83185 03259",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Local Listings / Indian Oil"
  },
  {
    "id": "LK-I02",
    "name": "IOCL - Sai Charging Point",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (2 Slots, Likely AC/DC <50kW)",
    "type": "AC/DC (Standard Charger)",
    "timing": "Varies (Call to Confirm)",
    "location": "Ground Floor, NH 71, Sadar, Lakhmipur Baherwa, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9255,
    "longitude": 80.7674,
    "contact": "+91 94153 82868",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Local Listings / Indian Oil"
  },
  {
    "id": "LK-I03",
    "name": "IOCL - Radha Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (2 Slots, Likely AC/DC <50kW)",
    "type": "AC/DC (Standard Charger)",
    "timing": "24/7 (Fuel Station Hours)",
    "location": "Ground Floor, Islamabad ZA Mohammadi, Mohammdi Road Gola Road, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 28.0740,
    "longitude": 80.4500,
    "contact": "+91 94151 62128",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Indian Oil Official Locator"
  },
  {
    "id": "LK-I04",
    "name": "IOCL - Kamla Kisan Sewa Kendra",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (2 Slots, Likely AC/DC <50kW)",
    "type": "AC/DC (Standard Charger)",
    "timing": "Until 10:00 PM (Daily)",
    "location": "Ground Floor, Behjam Baherwa Near KM Stone 2 to 6, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9300,
    "longitude": 80.7600,
    "contact": "1800 233 3555",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Indian Oil Official Locator"
  },
  {
    "id": "LK-I05",
    "name": "IOCL - Sai Baba Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (2 Slots, Likely AC/DC <50kW)",
    "type": "AC/DC (Standard Charger)",
    "timing": "06:00 AM - 10:00 PM (Daily)",
    "location": "Ground Floor, Bhandsariya Baherwa, Bahraich Road Gola Road, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.9300,
    "longitude": 80.7600,
    "contact": "+91 80099 95112",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Indian Oil Official Locator"
  },
  {
    "id": "LK-H01",
    "name": "HPCL - Hamara Pump Malti Devi",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (1 Slot, Likely Bharat AC-001)",
    "type": "AC/DC (Standard Charger)",
    "timing": "05:00 AM - 10:00 PM (Daily)",
    "location": "Ground Floor, Pipri, Behjam, Bhulanpur, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.8760,
    "longitude": 80.7580,
    "contact": "+91 95651 56656",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Hindustan Petroleum Official Locator"
  },
  {
    "id": "LK-H02",
    "name": "HPCL - Raj Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (1 Slot, Likely AC Type 2)",
    "type": "AC/DC (Standard Charger)",
    "timing": "24/7 (Fuel Station Hours)",
    "location": "Ground Floor, NH 30, Mohammadi, Hariharpur, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 28.0050,
    "longitude": 80.4200,
    "contact": "+91 95541 84444",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Hindustan Petroleum Official Locator"
  },
  {
    "id": "LK-H03",
    "name": "HPCL - Hamara Aradhya Charging Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (1 Slot, Likely Bharat AC-001)",
    "type": "AC/DC (Standard Charger)",
    "timing": "Until 10:00 PM (Daily)",
    "location": "Ground Floor, Kazi Kamalpur Kasta Road, Mitauli, Pipra Jhala, Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "latitude": 27.8018,
    "longitude": 80.5802,
    "contact": "+91 89578 32105",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Hindustan Petroleum Official Locator"
  },
  {
    "id": "LK-S01",
    "name": "Statiq - Shreyash Filling Station",
    "district": "Lakhimpur Kheri",
    "capacity": "Not Specified (Capacity Varies)",
    "type": "AC/DC (Fast/Standard Charger - Varies)",
    "timing": "Varies (Call Statiq Support)",
    "location": "BEHRAICH RD, LAKHIMPURKHERI",
    "state": "Uttar Pradesh",
    "latitude": 27.9478,
    "longitude": 80.7766,
    "contact": "Statiq Support (General)",
    "image": "https://maps.google.com/maps?cid=someimageid",
    "source": "Statiq Network Listings"
  },
  {
    "id": "JNP-IOCL-PRASAD-01",
    "name": "IOCL Prasad Charging Station",
    "district": "Jaunpur",
    "capacity": "2 connectors (Bharat AC-001 / Type-II)",
    "type": "AC",
    "timing": "24/7",
    "location": "NH 731, Badlapur Bypass, Sarokhanpur, Jaunpur Sultan Road, Jaunpur, Uttar Pradesh-222125",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": "9451266662",
    "image": null,
    "source": "ZigWheels – Electric Car Charging Stations in Jaunpur"
  },
  {
    "id": "JNP-IOCL-MANIKALA-01",
    "name": "IOCL KSK Manikala Charging Station",
    "district": "Jaunpur",
    "capacity": "2 connectors (Bharat AC-001 + Type-II)",
    "type": "AC",
    "timing": "As per pump hours",
    "location": "Manikala, Shahganj-Arand, Jaunpur, Uttar Pradesh 222139",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": "9919043029",
    "image": null,
    "source": "ZigWheels / IndianOil locator"
  },
  {
    "id": "JNP-HPCL-DEV-01",
    "name": "HPCL Dev Charging Station",
    "district": "Jaunpur",
    "capacity": "3 connectors (AC — slot-3)",
    "type": "AC",
    "timing": "As per pump hours",
    "location": "Takha Mariyam West, Jaunpur, Uttar Pradesh",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": null,
    "image": null,
    "source": "ZigWheels – Jaunpur EV-charging list"
  },
  {
    "id": "JNP-IOCL-MAA-MALTI-01",
    "name": "IOCL Maa Malti KSK Charging Station",
    "district": "Jaunpur",
    "capacity": "2 connectors (Bharat AC-001 + Type-II)",
    "type": "AC",
    "timing": "As per pump hours",
    "location": "Gaura Badshahpur, Sadar / Saloni Mahimapur, Jaunpur, Uttar Pradesh",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": "9415633849",
    "image": null,
    "source": "ZigWheels – Jaunpur EV-charging list"
  },
  {
    "id": "BBK-S01",
    "name": "Statiq - Radhey Radhey Filling Station",
    "district": "Barabanki",
    "capacity": "1 DC Fast Connector (60kW) + AC Connectors",
    "type": "AC/DC",
    "timing": "24/7",
    "location": "Mehndipur Road, Naanmau, Barabanki",
    "state": "Uttar Pradesh",
    "latitude": 26.9242,
    "longitude": 81.1925,
    "contact": "8070743743",
    "rating": 4.2,
    "source": "Statiq / PlugShare"
  },
  {
    "id": "BBK-I01",
    "name": "IOCL - Janta KSK Charging Station",
    "district": "Barabanki",
    "capacity": "1 Slot (AC/DC Standard)",
    "type": "AC/DC",
    "timing": "06:00 AM - 10:00 PM",
    "location": "Zaidpur Road, Kola Gahbadi Harakh, Barabanki",
    "state": "Uttar Pradesh",
    "latitude": 26.8520,
    "longitude": 81.3155,
    "contact": "9794880994",
    "rating": 4.0,
    "source": "Indian Oil / ZigWheels"
  },
  {
    "id": "BBK-I02",
    "name": "IOCL - L.S.D.P Kisan Sewa Kendra",
    "district": "Barabanki",
    "capacity": "2 Slots (Bharat AC-001, Type-II)",
    "type": "AC",
    "timing": "10:00 AM - 07:00 PM",
    "location": "Ayodhya-Faizabad Road, Rudauli, Barabanki",
    "state": "Uttar Pradesh",
    "latitude": 26.7485,
    "longitude": 81.7420,
    "contact": "9454462212",
    "rating": 3.8,
    "source": "ZigWheels / Indian Oil"
  },
  {
    "id": "BBK-I03",
    "name": "IOCL - Bapu KSK Charging Station",
    "district": "Barabanki",
    "capacity": "1 Slot (Fast Charger)",
    "type": "DC",
    "timing": "10:00 AM - 07:00 PM",
    "location": "Deva Road, Shahpur, Barabanki",
    "state": "Uttar Pradesh",
    "latitude": 26.9645,
    "longitude": 81.2050,
    "contact": "7829330410",
    "rating": 4.1,
    "source": "Indian Oil"
  },
  {
    "id": "BBK-H01",
    "name": "HPCL - Renu Charging Station",
    "district": "Barabanki",
    "capacity": "1 Slot (Standard AC)",
    "type": "AC",
    "timing": "24/7",
    "location": "Village-Jamin, Tehsil-Haidergarh, Barabanki",
    "state": "Uttar Pradesh",
    "latitude": 26.6120,
    "longitude": 81.3480,
    "contact": "9415162128",
    "rating": 3.7,
    "source": "HPCL Official"
  },
  {
    "id": "BBK-S02",
    "name": "Statiq - Aditya Fuel Pump",
    "district": "Barabanki",
    "capacity": "2 CCS-2 Connectors (60kW)",
    "type": "DC Fast",
    "timing": "24/7",
    "location": "Village Udhauli, Pargana Pratapganj, Tehsil Nawabganj",
    "state": "Uttar Pradesh",
    "latitude": 26.9412,
    "longitude": 81.1856,
    "contact": "8070743743",
    "rating": 4.4,
    "source": "Statiq Network"
  },
  {
    "id": "VAR-TATA-01",
    "name": "Tata Power - Taj Ganges Hotel CCS",
    "district": "Varanasi",
    "capacity": "CCS2 DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Nadesar, Chaukaghat, Varanasi",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": null,
    "rating": 4.5,
    "source": "Tata Power"
  }, {
    "id": "VAR-TATA-02",
    "name": "Tata Power - Brijlax Shivpur",
    "district": "Varanasi",
    "capacity": "DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Tarna, Ganeshpur, Shivpur, Varanasi",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": null,
    "rating": null,
    "source": "Tata Power"
  },
  {
    "id": "VAR-TATA-03",
    "name": "Tata Power - Hotel Tridev Grand",
    "district": "Varanasi",
    "capacity": "DC Fast (Multiple Guns)",
    "type": "DC",
    "timing": "24/7",
    "location": "Sankat Mochan Road, Tulsi Manas Mandir Colony, Naria, Varanasi",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": null,
    "rating": null,
    "source": "Tata Power"
  },
  {
    "id": "VAR-IOC-01",
    "name": "Indian Oil - GD Filling Station",
    "district": "Varanasi",
    "capacity": "DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Harsos, Varanasi",
    "state": "Uttar Pradesh",
    "latitude": null,
    "longitude": null,
    "contact": null,
    "rating": null,
    "source": "Indian Oil"
  },
  {
    "id": "PRY-01",
    "name": "Hotel Rama International Civil Lines",
    "district": "Prayagraj",
    "capacity": "CCS2 DC Fast",
    "type": "DC/AC",
    "timing": "24/7",
    "location": "Tashkent Marg, Civil Lines, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.4511,
    "longitude": 81.8463,
    "contact": "N/A",
    "rating": 4.2,
    "source": "Statiq"
  },
  {
    "id": "PRY-02",
    "name": "Prayag Udyog NH27",
    "district": "Prayagraj",
    "capacity": "DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "NH27, Mumtaj Nagar, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.4359,
    "longitude": 81.9333,
    "contact": "N/A",
    "rating": 4.1,
    "source": "Statiq"
  },
  {
    "id": "PRY-03",
    "name": "Ather Grid Charging Station",
    "district": "Prayagraj",
    "capacity": "AC",
    "type": "AC",
    "timing": "Daytime",
    "location": "Central Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.4511,
    "longitude": 81.8463,
    "contact": "88845 44933",
    "rating": 4.0,
    "source": "Ather"
  },
  {
    "id": "PRY-04",
    "name": "IOCL Jay Kisan Seva Kendra",
    "district": "Prayagraj",
    "capacity": "Bharat DC-001",
    "type": "DC",
    "timing": "24/7",
    "location": "Bajahi, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.4000,
    "longitude": 81.8000,
    "contact": "18002333555",
    "rating": 4.3,
    "source": "IOCL"
  },
  {
    "id": "PRY-05",
    "name": "HPCL Prabhavati Charging Station",
    "district": "Prayagraj",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "24/7",
    "location": "Post-Khunta, Tehsil-Meja, Prayagraj",
    "state": "Uttar Pradesh",
    "latitude": 25.3000,
    "longitude": 81.9000,
    "contact": "N/A",
    "rating": 4.0,
    "source": "HPCL"
  },
  {
    "id": "PRY-01",
    "name": "IOCL - Airport Charging Station",
    "district": "Prayagraj",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Ground Floor, Katahula Gauspur, Sadar, Bamrauli Asrawey Kalan",
    "state": "Uttar Pradesh",
    "latitude": 25.4426,
    "longitude": 81.7324,
    "contact": "7505608076",
    "rating": 4.2,
    "source": "IOCL"
  },
  {
    "id": "PRY-02",
    "name": "IOCL - Amar Ram Charging Station",
    "district": "Prayagraj",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Ground Floor, Amiliya Kala, Meja, Urwa Achhola",
    "state": "Uttar Pradesh",
    "latitude": 25.1726,
    "longitude": 81.9968,
    "contact": "8858706711",
    "rating": 4.1,
    "source": "IOCL"
  },
  {
    "id": "PRY-03",
    "name": "IOCL - Amar Singh Ksk Charging Station",
    "district": "Prayagraj",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Ground Floor, Manikapur, Phulpur Sahson",
    "state": "Uttar Pradesh",
    "latitude": 25.4685,
    "longitude": 82.2213,
    "contact": "7985304122",
    "rating": 4.0,
    "source": "IOCL"
  },
  {
    "id": "PRY-04",
    "name": "IOCL - Panjtan Kisan Seva Kendra",
    "district": "Prayagraj",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "24/7",
    "location": "Ground Floor, Buapur, Phulpur Soraon",
    "state": "Uttar Pradesh",
    "latitude": 25.5477,
    "longitude": 82.0894,
    "contact": "9918300200",
    "rating": 4.3,
    "source": "IOCL"
  },
  {
    "id": "PRY-05",
    "name": "IOCL - Jay Kisan Seva Kendra",
    "district": "Prayagraj",
    "capacity": "Bharat DC-001",
    "type": "DC",
    "timing": "24/7",
    "location": "Bajahi",
    "state": "Uttar Pradesh",
    "latitude": 25.4000,
    "longitude": 81.8000,
    "contact": "18002333555",
    "rating": 4.2,
    "source": "IOCL"
  },
  {
    "id": "AGR-01",
    "name": "Statiq - ITC Mughal Station",
    "district": "Agra",
    "capacity": "2 CCS2 DC (120kW)",
    "type": "DC Fast",
    "timing": "24/7",
    "location": "Tajganj, Fatehabad Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1607,
    "longitude": 78.0439,
    "contact": "8070743743",
    "rating": 4.5,
    "source": "Statiq"
  },
  {
    "id": "AGR-02",
    "name": "Tata Power - Trident Hotel",
    "district": "Agra",
    "capacity": "2 CCS2 DC (60kW)",
    "type": "DC Fast",
    "timing": "24/7",
    "location": "Fatehabad Road, Basai Khurd, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1592,
    "longitude": 78.0608,
    "contact": "8171369204",
    "rating": 4.6,
    "source": "Tata Power"
  },
  {
    "id": "AGR-03",
    "name": "IOCL - Taj Parking Shilpgram",
    "district": "Agra",
    "capacity": "1 CCS2 DC (60kW)",
    "type": "DC Fast",
    "timing": "24/7",
    "location": "Shilpgram, Tajganj, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1663,
    "longitude": 78.0522,
    "contact": "18002333555",
    "rating": 4.4,
    "source": "Indian Oil"
  },
  {
    "id": "AGR-04",
    "name": "UPEIDA - Agra Toll Plaza",
    "district": "Agra",
    "capacity": "Dual Gun DC (240kW)",
    "type": "DC Ultra-Fast",
    "timing": "24/7",
    "location": "Agra-Lucknow Expressway, Bichola",
    "state": "Uttar Pradesh",
    "latitude": 27.0572,
    "longitude": 78.2727,
    "contact": "N/A",
    "rating": 4.7,
    "source": "UPEIDA"
  },
  {
    "id": "AGR-05",
    "name": "Jio-BP Pulse - MG Road",
    "district": "Agra",
    "capacity": "60kW DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Near Agra College, MG Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1755,
    "longitude": 78.0085,
    "contact": "18008910300",
    "rating": 4.3,
    "source": "Jio-BP"
  },
  {
    "id": "AGR-06",
    "name": "Statiq - Jaypee Palace Hotel",
    "district": "Agra",
    "capacity": "2 CCS2 DC (120kW)",
    "type": "DC Fast",
    "timing": "24/7",
    "location": "Fatehabad Road, Kalal Kheria, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1526,
    "longitude": 78.0717,
    "contact": "8070743743",
    "rating": 4.5,
    "source": "Statiq"
  },
  {
    "id": "AGR-07",
    "name": "Kazam - Hotel Clark Shiraz",
    "district": "Agra",
    "capacity": "7.4kW AC Type-2",
    "type": "AC",
    "timing": "24/7",
    "location": "54, Taj Road, Agra Cantt",
    "state": "Uttar Pradesh",
    "latitude": 27.1620,
    "longitude": 78.0190,
    "contact": "9999123456",
    "rating": 4.1,
    "source": "Kazam"
  },
  {
    "id": "AGR-08",
    "name": "Tata Power - MG Motors Agra",
    "district": "Agra",
    "capacity": "50kW DC Fast",
    "type": "DC",
    "timing": "10 AM - 7 PM",
    "location": "NH-2, Delhi-Agra Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.2155,
    "longitude": 77.9450,
    "contact": "8527000290",
    "rating": 4.2,
    "source": "Tata Power"
  },
  {
    "id": "AGR-09",
    "name": "Ather Grid - Sanjay Place",
    "district": "Agra",
    "capacity": "3.3kW AC (2-Wheeler)",
    "type": "AC",
    "timing": "10 AM - 8 PM",
    "location": "Commercial Complex, Sanjay Place, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1950,
    "longitude": 78.0050,
    "contact": "8066465757",
    "rating": 4.0,
    "source": "Ather"
  },
  {
    "id": "AGR-10",
    "name": "Statiq - Courtyard by Marriott",
    "district": "Agra",
    "capacity": "22kW AC Type-2",
    "type": "AC",
    "timing": "24/7",
    "location": "Taj Nagri, Phase 2, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1585,
    "longitude": 78.0550,
    "contact": "8070743743",
    "rating": 4.4,
    "source": "Statiq"
  },
  {
    "id": "AGR-11",
    "name": "Tata Power - Holiday Inn",
    "district": "Agra",
    "capacity": "30kW DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Mahatma Gandhi Rd, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.2020,
    "longitude": 78.0120,
    "contact": "8527000290",
    "rating": 4.3,
    "source": "Tata Power"
  },
  {
    "id": "AGR-12",
    "name": "Jio-BP - Kuber Pur Hub",
    "district": "Agra",
    "capacity": "60kW DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Kuber Pur, Yamuna Expressway Exit, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.2250,
    "longitude": 78.1250,
    "contact": "18008910300",
    "rating": 4.5,
    "source": "Jio-BP"
  },
  {
    "id": "AGR-13",
    "name": "IOCL - Radisson Hotel Road",
    "district": "Agra",
    "capacity": "Bharat AC-001",
    "type": "AC",
    "timing": "24/7",
    "location": "Taj Nagri, Near Radisson Hotel, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1590,
    "longitude": 78.0580,
    "contact": "N/A",
    "rating": 3.9,
    "source": "Indian Oil"
  },
  {
    "id": "AGR-14",
    "name": "GLIDA - DoubleTree by Hilton",
    "district": "Agra",
    "capacity": "DC Fast (60kW)",
    "type": "DC",
    "timing": "24/7",
    "location": "Taj Nagri Phase II, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1555,
    "longitude": 78.0620,
    "contact": "9876543210",
    "rating": 4.5,
    "source": "GLIDA"
  },
  {
    "id": "AGR-15",
    "name": "Statiq - Crystal Sarovar Premiere",
    "district": "Agra",
    "capacity": "Type-2 AC (7.4kW)",
    "type": "AC",
    "timing": "24/7",
    "location": "Fatehabad Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1580,
    "longitude": 78.0480,
    "contact": "8070743743",
    "rating": 4.2,
    "source": "Statiq"
  },
  {
    "id": "AGR-16",
    "name": "Tata Power - Kia Motors Agra",
    "district": "Agra",
    "capacity": "25kW DC Fast",
    "type": "DC",
    "timing": "10 AM - 7 PM",
    "location": "NH-2, Transport Nagar, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.2080,
    "longitude": 77.9650,
    "contact": "8527000290",
    "rating": 4.1,
    "source": "Tata Power"
  },
  {
    "id": "AGR-17",
    "name": "Zeon Charging - Highway Treat",
    "district": "Agra",
    "capacity": "50kW DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "NH-2, Agra-Delhi Road",
    "state": "Uttar Pradesh",
    "latitude": 27.3500,
    "longitude": 77.7500,
    "contact": "9876543210",
    "rating": 4.6,
    "source": "Zeon"
  },
  {
    "id": "AGR-18",
    "name": "HPCL - Agra Cantt Station",
    "district": "Agra",
    "capacity": "AC Type-2",
    "type": "AC",
    "timing": "24/7",
    "location": "Agra Cantt Railway Station Area, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1585,
    "longitude": 78.0100,
    "contact": "N/A",
    "rating": 3.8,
    "source": "HPCL"
  },
  {
    "id": "AGR-19",
    "name": "Kazam - Hotel Mansingh",
    "district": "Agra",
    "capacity": "3.3kW AC Points",
    "type": "AC",
    "timing": "24/7",
    "location": "Fatehabad Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1610,
    "longitude": 78.0350,
    "contact": "9999123456",
    "rating": 4.0,
    "source": "Kazam"
  },
  {
    "id": "AGR-20",
    "name": "Statiq - Ramada Plaza",
    "district": "Agra",
    "capacity": "CCS2 DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Inner Ring Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1420,
    "longitude": 78.1050,
    "contact": "8070743743",
    "rating": 4.4,
    "source": "Statiq"
  },
  {
    "id": "AGR-21",
    "name": "Tata Power - Hyundai Samit",
    "district": "Agra",
    "capacity": "AC Level 2",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Bye Pass Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.2100,
    "longitude": 78.0150,
    "contact": "8527000290",
    "rating": 3.9,
    "source": "Tata Power"
  },
  {
    "id": "AGR-22",
    "name": "PlugNgo - Taj East Gate Parking",
    "district": "Agra",
    "capacity": "DC Fast 30kW",
    "type": "DC",
    "timing": "6 AM - 10 PM",
    "location": "Taj East Gate, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1625,
    "longitude": 78.0610,
    "contact": "N/A",
    "rating": 4.3,
    "source": "PlugNgo"
  },
  {
    "id": "AGR-23",
    "name": "Jio-BP Pulse - Sikandra Hub",
    "district": "Agra",
    "capacity": "60kW DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Sikandra, NH-2, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.2210,
    "longitude": 77.9350,
    "contact": "18008910300",
    "rating": 4.2,
    "source": "Jio-BP"
  },
  {
    "id": "AGR-24",
    "name": "Ather Grid - Dayalbagh",
    "district": "Agra",
    "capacity": "Fast Charging for 2W",
    "type": "AC",
    "timing": "10 AM - 9 PM",
    "location": "Dayalbagh Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.2150,
    "longitude": 78.0125,
    "contact": "8066465757",
    "rating": 4.1,
    "source": "Ather"
  },
  {
    "id": "AGR-25",
    "name": "Statiq - Howard Plaza",
    "district": "Agra",
    "capacity": "7.4kW AC Type-2",
    "type": "AC",
    "timing": "24/7",
    "location": "Fatehabad Road, Agra",
    "state": "Uttar Pradesh",
    "latitude": 27.1615,
    "longitude": 78.0410,
    "contact": "8070743743",
    "rating": 4.3,
    "source": "Statiq"
  },
  {
    "id": "BLY-01",
    "name": "Tata Power - MG Keshav Raj",
    "district": "Bareilly",
    "capacity": "CCS2 DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "4.5 KM Rampur Road, C.B. Ganj, Bareilly-243001",
    "state": "Uttar Pradesh",
    "latitude": 28.3800,
    "longitude": 79.4200,
    "contact": "18008332233",
    "rating": 4.5,
    "source": "Tata Power"
  },
  {
    "id": "BLY-02",
    "name": "Sparsh Hotels by Clarks Collection",
    "district": "Bareilly",
    "capacity": "AC Type 2",
    "type": "AC",
    "timing": "24/7",
    "location": "Opp. Suresh Sharma Nagar Chauraha, Pilibhit By-Pass Road, Bareilly-243001",
    "state": "Uttar Pradesh",
    "latitude": 28.3700,
    "longitude": 79.4300,
    "contact": "N/A",
    "rating": 4.2,
    "source": "Statiq"
  },
  {
    "id": "BLY-03",
    "name": "IOCL - Ashok Charging Station",
    "district": "Bareilly",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Ashok Marg, Civil Lines, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.3682,
    "longitude": 79.4315,
    "contact": "9412605486",
    "rating": 4.1,
    "source": "IOCL"
  },
  {
    "id": "BLY-04",
    "name": "IOCL - Kanman Filling Charging Station",
    "district": "Bareilly",
    "capacity": "AC Type 2",
    "type": "AC",
    "timing": "24/7",
    "location": "Kanman Road, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.3900,
    "longitude": 79.4100,
    "contact": "N/A",
    "rating": 4.0,
    "source": "IOCL"
  },
  {
    "id": "BLY-05",
    "name": "IOCL - Prabhu Narayan Charging Station",
    "district": "Bareilly",
    "capacity": "16 Amp AC",
    "type": "AC",
    "timing": "6 AM - 10 PM",
    "location": "Pilibhit Road, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.3770,
    "longitude": 79.4520,
    "contact": "7829330410",
    "rating": 4.3,
    "source": "IOCL"
  },
  {
    "id": "BLY-06",
    "name": "IOCL - Shahi Kisan Sewa Kendra",
    "district": "Bareilly",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Ground Floor, Dharampur Shahi, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.3840,
    "longitude": 79.4179,
    "contact": "9412605486",
    "rating": 4.2,
    "source": "IOCL"
  },
  {
    "id": "BLY-07",
    "name": "IOCL - Tirupati Service Charging Station",
    "district": "Bareilly",
    "capacity": "AC Type 2",
    "type": "AC",
    "timing": "24/7",
    "location": "Village Shahpurmustkil, Sirauli To Shahabad Road, Tehsil Aonla",
    "state": "Uttar Pradesh",
    "latitude": 28.3950,
    "longitude": 79.4500,
    "contact": "8077132951",
    "rating": 4.1,
    "source": "IOCL"
  },
  {
    "id": "BLY-08",
    "name": "IOCL - Rajpal Charging Station",
    "district": "Bareilly",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Nainital Road, Baheri, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.3850,
    "longitude": 79.4150,
    "contact": "9412287022",
    "rating": 4.0,
    "source": "IOCL"
  },
  {
    "id": "BLY-09",
    "name": "IOCL - Dayal Ksk Charging Station",
    "district": "Bareilly",
    "capacity": "Bharat AC001",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Shahi Shergarh Road, Shergarh, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.4000,
    "longitude": 79.4000,
    "contact": "9359103724",
    "rating": 4.2,
    "source": "IOCL"
  },
  {
    "id": "BLY-10",
    "name": "Ather Grid Charging Station",
    "district": "Bareilly",
    "capacity": "AC Fast",
    "type": "AC",
    "timing": "24/7",
    "location": "A-5, Rajendra Nagar, Bareilly-243122",
    "state": "Uttar Pradesh",
    "latitude": 28.3600,
    "longitude": 79.4300,
    "contact": "7676600900",
    "rating": 4.4,
    "source": "Ather Grid"
  },
  {
    "id": "BLY-11",
    "name": "Tata Power - Batkeshwar Ksk",
    "district": "Bareilly",
    "capacity": "CCS-II",
    "type": "DC",
    "timing": "10 AM - 7 PM",
    "location": "Village Bhoora Bhadrol, Tehsil Badaun Ujhani Badaun Road",
    "state": "Uttar Pradesh",
    "latitude": 28.4100,
    "longitude": 79.3800,
    "contact": "N/A",
    "rating": 4.3,
    "source": "Tata Power"
  },
  {
    "id": "BLY-12",
    "name": "Statiq - Ramada Bareilly",
    "district": "Bareilly",
    "capacity": "DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Ramada Hotel Area, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.3770,
    "longitude": 79.4520,
    "contact": "N/A",
    "rating": 4.4,
    "source": "Statiq"
  },
  {
    "id": "BLY-13",
    "name": "IOCL - Dhamkhoda Charging Station",
    "district": "Bareilly",
    "capacity": "AC Type 2",
    "type": "AC",
    "timing": "10 AM - 7 PM",
    "location": "Ground Floor, Bareilly Dhamkhoda",
    "state": "Uttar Pradesh",
    "latitude": 28.3850,
    "longitude": 79.4150,
    "contact": "9412643032",
    "rating": 4.1,
    "source": "IOCL"
  },
  {
    "id": "BLY-14",
    "name": "Radha Kishan Filling Station",
    "district": "Bareilly",
    "capacity": "AC",
    "type": "AC",
    "timing": "24/7",
    "location": "2021108 - Radha Kishan Filling Station",
    "state": "Uttar Pradesh",
    "latitude": 28.3900,
    "longitude": 79.4200,
    "contact": "N/A",
    "rating": 4.0,
    "source": "Local"
  },
  {
    "id": "BLY-15",
    "name": "Keshav Raj Automobiles",
    "district": "Bareilly",
    "capacity": "CCS2",
    "type": "DC",
    "timing": "10 AM - 8 PM",
    "location": "Rampur Road, C.B. Ganj",
    "state": "Uttar Pradesh",
    "latitude": 28.3805,
    "longitude": 79.4195,
    "contact": "N/A",
    "rating": 4.5,
    "source": "123EV"
  },
  {
    "id": "BLY-16",
    "name": "Statiq - Civil Lines Station",
    "district": "Bareilly",
    "capacity": "DC Fast",
    "type": "DC",
    "timing": "24/7",
    "location": "Civil Lines, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.3680,
    "longitude": 79.4320,
    "contact": "8070743743",
    "rating": 4.3,
    "source": "Statiq"
  },
  {
    "id": "BLY-17",
    "name": "HPCL - Bareilly Highway Station",
    "district": "Bareilly",
    "capacity": "Bharat DC",
    "type": "DC",
    "timing": "24/7",
    "location": "NH-30, Bareilly Bypass",
    "state": "Uttar Pradesh",
    "latitude": 28.3950,
    "longitude": 79.4350,
    "contact": "N/A",
    "rating": 4.2,
    "source": "HPCL"
  },
  {
    "id": "BLY-18",
    "name": "JioBP - Rajendra Nagar",
    "district": "Bareilly",
    "capacity": "Fast DC",
    "type": "DC",
    "timing": "24/7",
    "location": "Rajendra Nagar, Bareilly",
    "state": "Uttar Pradesh",
    "latitude": 28.3605,
    "longitude": 79.4295,
    "contact": "18008909023",
    "rating": 4.4,
    "source": "JioBP"
  },

];

module.exports = stations;
